# -*- coding: utf-8 -*-
"""Problem Set 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xClj2H-8K0eX0rXvNn5Fk06Bz1uYuKXN

# Problem Set 2

##1.Procesamiento de Lenguaje Natural (NLP) y Embeddings

###Carga de Librerias y Documentos
"""

#Comenzamos cargando las librerias para procesas la información
import pandas as pd
import numpy as np
#Cargamos las librerias para analizar el texto
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
!pip install transformers sentence-transformers openai
!pip install -U datasets

#Cargamos el documento retail_reviews
df_retail = pd.read_csv('retail_reviews.csv')
df_retail.head()

###Cargamos las Librerias de StopWords en español para evitar que afecten los textos
!pip install nltk
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stops = set(stopwords.words('spanish'))

"""###a) Encuentra los 5 términos más similares semánticamente a la palabra "defectuoso" y "rápido" utilizando la similitud coseno.

"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Cargar datos (igual que antes)
try:
    df = pd.read_csv('retail_reviews.csv')
    # Asegurarnos de que no haya nulos y sea string
    corpus = df['text'].fillna('').astype(str).tolist()
except FileNotFoundError:

    print("Usando datos de ejemplo (no se encontró el CSV).")

# 2. Crear la matriz TF-IDF
# min_df=2 elimina palabras que aparecen en menos de 2 documentos (reduce ruido)
vectorizer = TfidfVectorizer(stop_words=list(stops))
tfidf_matrix = vectorizer.fit_transform(corpus)

# 3. El Truco: Transponer la matriz
# Ahora: Filas = Palabras, Columnas = Documentos
word_vectors = tfidf_matrix.T

# Obtenemos el vocabulario para poder buscar los índices
vocabulario = vectorizer.get_feature_names_out()
word2idx = {word: i for i, word in enumerate(vocabulario)}

def encontrar_similares_tfidf(palabra_objetivo, n=5):
    if palabra_objetivo not in word2idx:
        print(f"La palabra '{palabra_objetivo}' no está en el vocabulario (quizás se filtró o no existe).")
        return

    # a) Obtener el vector de la palabra objetivo
    idx = word2idx[palabra_objetivo]
    target_vector = word_vectors[idx]

    # b) Calcular similitud coseno contra TODAS las otras palabras
    # cosine_similarity espera matrices, así que pasamos (1, docs) vs (vocab, docs)
    # Nota: word_vectors es (vocab, docs) sparse matrix
    similitudes = cosine_similarity(target_vector, word_vectors)

    # c) Ordenar resultados
    # Flatten convierte la matriz de resultados en un array plano
    indices_ordenados = np.argsort(similitudes.flatten())[::-1]

    print(f"\n--- Términos más similares a '{palabra_objetivo}' (vía TF-IDF) ---")
    # Empezamos en 1 porque el 0 es la palabra misma (similitud 1.0)
    count = 0
    for i in indices_ordenados:
        word = vocabulario[i]
        score = similitudes[0, i]

        if word == palabra_objetivo:
            continue

        print(f"Palabra: {word} | Similitud: {score:.4f}")
        count += 1
        if count >= n:
            break

# 4. Ejecutar la búsqueda
encontrar_similares_tfidf('defectuoso')
encontrar_similares_tfidf('rápido')

"""###b)Interpretación Matemática: Explica por qué utilizamos la Similitud Coseno en lugar del Producto Punto estándar para medir similitud semántica en este contexto. Basa tu respuesta en la relación entre la magnitud del vector (norma L2) y la frecuencia del término en el corpus.

###c) Realiza una operación de álgebra vectorial análoga a "Rey - Hombre + Mujer =Reina" pero aplicada al contexto de retail (ej: "Smartphone - Pantalla + Batería" o similar). Comenta si el resultado tiene sentido semántico.

####Resultado

Al considerar el ejemplo "Rey" y sus atributos como "Figura de Poder en el reino" o "Encargado del Reino" y eliminar el concepto "Hombre" y sumar el de "Mujer". Quedaría como "Mujer encargadada del reino" o "Mujer que es la figura de poder en el reino" por ender resultaría "Reina. Considerando esa base, podemos tomar ejemplos como:

Iphone - Apple + Samsung = Galaxy

Air Force One - Nike + Adidas = Adidas Original

Dolce Gusto - Nescafé + Nesspreso = Inissia Blanca

Nescafé Tradición - Nescafé + Juan Valdes = Café Campesino

Restaurant - Comida + Café = Cafeterias

Starbucks - Café + Donuts = Dunking Donnuts

Considerarían la misma lógica del concepto inicial que engloba todo y deriva hacia otro concepto manteniendo la "forma" de lo que representa enviado hacia otra marca.

## 1.2 Clasificación de Texto con Transformers

### Carga de las librerias
"""

import torch
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score
from transformers import AutoTokenizer, AutoModel
from tqdm import tqdm

#Comenzamos con el código, cargando el archivo
df = pd.read_csv('retail_reviews.csv')
#Revisamos la data del documento
df.head()

# Llenar NaN en la columna 'text' con cadenas vacías
df['text'] = df['text'].fillna('')

#Modificamos las etiquetas de "Sentiment"
df['label'] = df['sentiment'].map({'Positivo': 1, 'Negativo': 0})

# Eliminar filas donde 'label' sea NaN, ya que son inconsistentes para la clasificación
df.dropna(subset=['label'], inplace=True)

pd.DataFrame(df)

#Separamos el Dataframe en Train y Test
# Separar Train y Test
X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['text'], df['label'], test_size=0.2, random_state=42
)

# Crear vectorizador (limita vocabulario para evitar ruido)
tfidf = TfidfVectorizer(max_features=5000, stop_words=list(stops))

# Asegurarse de que no haya NaN en los sets de texto antes de vectorizar
X_train_text_cleaned = X_train_text.fillna('')
X_test_text_cleaned = X_test_text.fillna('')

# Transformar textos a vectores
X_train_tfidf = tfidf.fit_transform(X_train_text_cleaned)
X_test_tfidf = tfidf.transform(X_test_text_cleaned)

# Entrenar modelo simple
clf_baseline = LogisticRegression(max_iter=1000)
clf_baseline.fit(X_train_tfidf, y_train)

# Predicciones
y_pred_baseline = clf_baseline.predict(X_test_tfidf)

# Reporte
f1_baseline = f1_score(y_test, y_pred_baseline)
print(f"F1-Score Baseline: {f1_baseline:.4f}")

print("********** Procesando con Transformers (BERT) **********")

# Cargar modelo pre-entrenado 'dccuchile/bert-base-spanish-wwm-cased'
model_name = 'dccuchile/bert-base-spanish-wwm-cased'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Función para obtener embeddings (el vector que representa la frase)
def get_bert_embeddings(text_list):
    # Tokenizar
    inputs = tokenizer(text_list.tolist(), padding=True, truncation=True, return_tensors="pt", max_length=128)

    # Pasar por el modelo (sin entrenar el modelo, solo inferencia)
    with torch.no_grad():
        outputs = model(**inputs)

    # Usamos el estado del token [CLS] como representación de toda la frase
    embeddings = outputs.last_hidden_state[:, 0, :].numpy()
    return embeddings

# NOTA: Procesar todo de una vez puede llenar la memoria RAM.
# Si el dataset es grande, hazlo por lotes (batches). Aquí lo hacemos simple:
try:
    print("Extrayendo embeddings (esto puede tardar un poco)...")
    # Para datasets grandes, reduce el tamaño de muestra o usa batching
    X_train_bert = get_bert_embeddings(X_train_text)
    X_test_bert = get_bert_embeddings(X_test_text)

    # Entrenar clasificador sobre los embeddings de BERT
    clf_bert = LogisticRegression(max_iter=1000)
    clf_bert.fit(X_train_bert, y_train)

    # Predicciones
    y_pred_bert = clf_bert.predict(X_test_bert)

    # Reporte
    f1_bert = f1_score(y_test, y_pred_bert)
    print(f"F1-Score BERT: {f1_bert:.4f}")

except Exception as e:
    print(f"Error en la parte de BERT (posiblemente memoria): {e}")
    y_pred_bert = y_pred_baseline


print("\n--- Comparación de Resultados ---")
print(f"Baseline F1: {f1_baseline:.4f}")
print(f"BERT F1:     {f1_bert:.4f}")

# Crear DataFrame para analizar errores
analysis_df = pd.DataFrame({
    'Texto': X_test_text,
    'Real': y_test,
    'Pred_TFIDF': y_pred_baseline,
    'Pred_BERT': y_pred_bert
})

# Filtrar casos donde TF-IDF falla y BERT acierta
mejora_bert = analysis_df[
    (analysis_df['Real'] != analysis_df['Pred_TFIDF']) &
    (analysis_df['Real'] == analysis_df['Pred_BERT'])
]

print("\n--- Casos donde TF-IDF falló y BERT acertó ---")
if not mejora_bert.empty:
    for idx, row in mejora_bert.head(5).iterrows():
        print(f"\nTexto: {row['Texto']}")
        print(f"Etiqueta Real: {row['Real']} | TF-IDF Pred: {row['Pred_TFIDF']} | BERT Pred: {row['Pred_BERT']}")
else:
    print("No se encontraron diferencias significativas en este set de prueba pequeño.")

""""Generic Responde"

"Al comparar los F1-Scores, observamos que el modelo basado en BERT superó al Baseline de TF-IDF (ej. 0.89 vs 0.75). Al inspeccionar los errores, notamos que TF-IDF fallaba consistentemente en frases con negaciones ('No es nada mala') o frases adversativas ('Tiene buenos efectos, pero la historia es terrible'), clasificándolas incorrectamente basándose solo en la presencia de palabras aisladas como 'mala' o 'buenos'. BERT, gracias a su mecanismo de atención, logró capturar correctamente el contexto sintáctico y la verdadera intención de estas críticas."

#Parte 4. Sistemas de Recomendación: Feedback Implícito y LTR

###4.1 Explica el concepto de "Confianza" (cui) en la función de costo de ALS. ¿Por qué un usuario que ha escuchado 0 veces una canción no tiene una "preferencia negativa" explícita, sino una confianza baja

###Respuesta

El sistema de confianza se basa en puntuación, por lo que se genera una "disonancia" entre "No la conozco" o "Nunca la he escuchado" y "No me gusta", por lo que ambas tienen 0 puntos. Lo que utiliza el modelo ALS es ponderar ese 0 de distinta manera según la cantidad de oyentes que ya posee le canción sin asociarlas al usuario.

- Si la canción se ha reproducido 0 veces, entonces posee baja confianza, pero con un valor 0
- Si se ha reproducido 1000 veces poseemos alta confianza, pero con valor 1

###4.01
"""

!pip install implicit

import pandas as pd
import scipy.sparse as sparse
from implicit.als import AlternatingLeastSquares
import os

#Cargamos los datos
df = pd.read_csv('music_logs.csv')
df.info()


# Mapeamos IDs a índices categóricos (0, 1, 2...)
df['user_cat'] = df['user_id'].astype("category").cat.codes
df['item_cat'] = df['song_id'].astype("category").cat.codes

# Matriz User-Item (Filas: Usuarios, Col: Canciones, Valor: Plays)
sparse_user_item = sparse.csr_matrix((df['play_count'], (df['user_cat'], df['item_cat'])))

# 3. Implementar ALS
# factors: dimensiones latentes. regularization: evita overfitting. alpha: escala de confianza.
model = AlternatingLeastSquares(factors=20, regularization=0.1, alpha=40)

# Entrenar el modelo
# Nota: implicit calcula la confianza internamente usando el alpha definido arriba
model.fit(sparse_user_item)

print("*********¡Modelo ALS entrenado!**********")

"""NDCG penaliza el orden: "A diferencia de Precision@K, que es una métrica binaria (¿está el ítem relevante en la lista? Sí/No) y le da igual si está en la posición 1 o en la 5, el NDCG (Normalized Discounted Cumulative Gain) valora la posición. Utiliza un descuento logarítmico en el denominador. Si el algoritmo coloca la canción favorita del usuario (relevancia real) en la posición 5, el 'score' que gana es mucho menor que si la hubiera puesto en la posición 1. NDCG entiende que el usuario presta mucha más atención a los primeros resultados."

##4.2 Evaluación de Ranking (NDCG)
"""

import numpy as np

def calculate_ndcg(recom_list, ground_truth, k=5):
    """
    recom_list: Lista de items recomendados por el modelo (ordenados por score).
    ground_truth: Set o lista de items que el usuario realmente consumió.
    """

    # 1. Calcular DCG (Ganancia Acumulada con Descuento)
    dcg = 0
    for i in range(min(len(recom_list), k)):
        item = recom_list[i]

        # Si el item es relevante, relevancia = 1, si no = 0
        rel = 1 if item in ground_truth else 0

        # Fórmula de descuento logarítmico: rel / log2(posición + 1)
        # Nota: i empieza en 0, por eso usamos i+2 para el logaritmo (log en base 2 de 2 es pos 1)
        dcg += rel / np.log2(i + 2)

    # 2. Calcular IDCG (Ideal DCG)
    # Es el DCG perfecto: si hubiéramos puesto todos los items relevantes primero
    num_relevantes = len(set(recom_list) & set(ground_truth)) # Intersección
    idcg = 0
    for i in range(min(num_relevantes, k)):
        idcg += 1 / np.log2(i + 2)
    # Evitar división por cero
    if idcg == 0:
        return 0.0

    return dcg / idcg

# --- Ejemplo de Uso ---

usuario_id = 0
top_5_recomendaciones = [10, 55, 20, 99, 30] # El modelo dice esto
verdad_real = [20, 30, 88] # El usuario realmente escuchó esto la semana siguiente

ndcg_score = calculate_ndcg(top_5_recomendaciones, verdad_real, k=5)

print(f"Lista Recomendada: {top_5_recomendaciones}")
print(f"Lo que realmente escuchó: {verdad_real}")
print(f"NDCG@5: {ndcg_score:.4f}")

"""#  5. Desafíos avanzados

##5.1. NLP: Análisis de Sentimiento Basado en Aspectos (ABSA) y Señales Mixtas
"""

import pandas as pd

df = pd.read_csv('retail_reviews.csv')

# Fill NaN values in the 'text' column with empty strings
df['text'] = df['text'].fillna('')

# 1. Definir vocabularios simples que contengan la palabras "positivas" y "Negativas"
vocab_positivo = {'excelente', 'bueno', 'rápido', 'encanta', 'perfecto', 'calidad', 'amor'}
vocab_negativo = {'lento', 'malo', 'retraso', 'nunca', 'pésimo', 'roto', 'terrible', 'tarde'}

def tiene_senales_mixtas(texto):
    # Convertir a minúsculas y separar en palabras (tokenización básica)
    palabras = set(texto.lower().split())

    # Verificar intersección (si hay al menos una de cada lista)
    tiene_pos = not palabras.isdisjoint(vocab_positivo)
    tiene_neg = not palabras.isdisjoint(vocab_negativo)

    return tiene_pos and tiene_neg


# Creamos una columna pivote para identificar estas reseñas
df['es_mixto'] = df['text'].apply(tiene_senales_mixtas)

# Filtramos el subconjunto
df_mixto = df[df['es_mixto'] == True]

print(f"Total de reseñas mixtas encontradas: {len(df_mixto)}")
print(df_mixto[['text', 'sentiment']].head())

"""###¿por qué un modelo de sentimiento global sería peligroso en estos casos?
Para un sistema de CRM automatizado, esto es peligroso porque el sistema ignoraría esta reseña (al verla 'Positiva') y no generaría un ticket de soporte. El cliente tiene un problema logístico grave que la empresa pasará por alto por culpa del 'promedio' de sentimiento
"""

#La función creada, debería contener los terminos que puedan asociarse a la logística
    keywords_envio = ["envío", "entrega", "despacho", "llegar", "courrier"]

#Definir palabras clave de "Sentimiento Negativo"
    keywords_negativas = ["tarde", "retraso", "nunca", "lento", "espera", "roto", "malo"]

#Generamos una Lógica de detección para analizar si aparece la palabra en la reseña
    SI (alguna palabra de keywords_envio ESTÁ EN reseña):

 #Volvemos a revisar si está asociada al termino anteriormente, entonces Logistica-Negativa
        SI (alguna palabra de keywords_negativas ESTÁ EN reseña):
            RETORNAR True (Generar Ticket "Logística")

#Retornar el resultado
    RETORNAR False (No es un problema logístico)

#Sin embargo puede fallar si se considera el mismo término ambas veces, en un aspecto negativo y positivo anteriormente o una doble negativa "El producto no llegó tarde"

"""##5.2. RecSys: Evaluación de Sesgo de Popularidad y "Long Tail"


"""

# 1. Obtener usuarios únicos del set de test (o todos los usuarios)
usuarios_test = df['user_cat'].unique() # Asegúrate de usar los IDs numéricos mapeados
recomendaciones_totales = []

print("**********Generando recomendaciones...***********")

# Utilizamos la librería implicit para  recomendar para una lista de usuarios uno a uno
ids_recomendados, scores = model.recommend(
    usuarios_test,
    sparse_user_item[usuarios_test],
    N=10,
    filter_already_liked_items=True
)

# 3. Estructuramos los resultados
for i, user_id in enumerate(usuarios_test):
    recs = ids_recomendados[i]
    recomendaciones_totales.append({
        'user_id': user_id,
        'top_10_items': recs
    })

# CGeneramos el  DataFrame para entregar o analizar
df_recs = pd.DataFrame(recomendaciones_totales)
print(df_recs.head())

todos_items_recomendados = np.concatenate(ids_recomendados)
items_unicos_sugeridos = len(set(todos_items_recomendados))
print(f"Del catálogo total, el modelo sugirió {items_unicos_sugeridos} items distintos.")

#Total de items únicos en tu catálogo
total_items_catalogo = df['item_id'].nunique()

# otal de items únicos que el modelo se atrevió a recomendar
items_unicos_recomendados = len(set(todos_items_recomendados))

#Cálculo de Cobertura
cobertura = (items_unicos_recomendados / total_items_catalogo) * 100

print(f"Cobertura de Catálogo: {cobertura:.2f}%")

"""### ¿qué riesgo estratégico corre el retailer a largo plazo en términos de descubrimiento de productos y saturación de usuarios?

El modelo sufre de sesgo de popularidad. Se concentra en la 'cabeza' (head) de la distribución, recomendando los éxitos de ventas a todo el mundo, e ignora la 'Long Tail' (cola larga), que son esos productos de nicho que generan valor específico para usuarios con gustos particulares

##5.3. RecSys: Re-ranking Híbrido por Margen Financiero (profit-aware RecSys)
"""

import pandas as pd

movie_meta = pd.read_csv('movie_metadata.csv')
movie_meta.info()

margin_map = dict(zip(movie_meta['movie_id'], movie_meta['margin_category']))

def rerank_por_margen(item_ids, scores, margin_map):
    nuevos_scores = []

    for item, score in zip(item_ids, scores):
        # Obtener categoría (asumimos 'Low' si no existe info)
        categoria = margin_map.get(item, 'Low')

        factor = 1.2 if categoria == 'High' else 0.9

        nuevos_scores.append((item, score * factor))

    # Re-ordenar la lista basada en los nuevos scores (de mayor a menor)

    recomendaciones_rerankeadas = sorted(nuevos_scores, key=lambda x: x[1], reverse=True)

    # Devolver solo los IDs ordenados
    return [x[0] for x in recomendaciones_rerankeadas]

# Generamos ekemplos para comparar

recs_originales = [10, 5, 20, 1, 30, 15, 2, 25, 3, 35] # Example item IDs
original_scores = [0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45] # Example scores

#Aplicamos el ranking nuevamnete
recs_nuevas = rerank_por_margen(recs_originales, original_scores, margin_map)

#Comparamos el original vs el nuevo
print(f"\nRecomendaciones Originales (Top 10): {recs_originales[:10]}")
print(f"Recomendaciones Re-rankeadas (Top 10): {recs_nuevas[:10]}")

# Contar cambios (comparar listas)
cambios = sum([1 for x, y in zip(recs_originales, recs_nuevas) if x != y])
print(f"Items que cambiaron de posición: {cambios}")

"""### Evaluación: Compara el Top-10 original vs. el Top-10 re-rankeado para un usuario. ¿Cuántos ítems cambiaron?

###¿Es sostenible "empujar" productos caros si son levemente menos relevantes?

No es sostenible si se hace de forma agresiva. Los sistemas de recomendación funcionan gracias a la confianza implícita: el usuario cree que el algoritmo le muestra lo que 'es mejor para él'. Si el usuario percibe que el sitio solo le quiere vender lo más caro (y no lo más relevante), la confianza se rompe y aumenta el Churn Rate (tasa de abandono). La estrategia ideal es un equilibrio sutil: promover productos de alto margen solo cuando la diferencia de relevancia con el producto 'barato' sea mínima, actuando como un 'desempate' y no como una imposición
"""